# -*- coding: utf-8 -*-
"""session- 4_ 25bcon0956

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17G2p9hqICONYnMh7LpQ46zas19HFwJEH
"""

#include <stdio.h>

int main() {
    printf("Hello Colab");
    return 0;
}

print("Hello Colab")

#include <stdio.h>

int main() {
    int n, i;
    long long factorial = 1;

    printf("Enter a number: ");
    scanf("%d", &n);

    for (i = 1; i <= n; i++) {
        factorial = factorial * i;
    }

    printf("Factorial of %d = %lld", n, factorial);

    return 0;
}

def factorial(n):
    if n < 0:
        return "Factorial is not defined for negative numbers"
    elif n == 0:
        return 1
    else:
        fact = 1
        for i in range(1, n + 1):
            fact = fact * i
        return fact

# Simulate user input
number = 5  # Example input, can be changed
result = factorial(number)
print(f"Factorial of {number} = {result}")

#include <stdio.h>

int main() {
    int n, i;
    int a = 0, b = 1, next;

    printf("Enter the number of terms: ");
    scanf("%d", &n);

    printf("Fibonacci Series: ");

    for (i = 1; i <= n; i++) {
        printf("%d ", a);
        next = a + b;
        a = b;
        b = next;
    }

    return 0;
}

def fibonacci_series(n_terms):
    a, b = 0, 1
    series = []
    if n_terms <= 0:
        return "Please enter a positive integer"
    elif n_terms == 1:
        series.append(a)
    else:
        for _ in range(n_terms):
            series.append(a)
            next_term = a + b
            a = b
            b = next_term
    return series

# Simulate user input
num_terms = 10  # Example input, can be changed
fib_result = fibonacci_series(num_terms)
print(f"Fibonacci Series for {num_terms} terms: {', '.join(map(str, fib_result))}")

#include <stdio.h>
#include <string.h>

struct student {
    char name[50];
    int roll;
    float marks;
};

int main() {
    struct student s1;

    printf("Enter name: ");
    scanf("%s", s1.name);

    printf("Enter roll number: ");
    scanf("%d", &s1.roll);

    printf("Enter marks: ");
    scanf("%f", &s1.marks);

    printf("\nStudent Details\n");
    printf("Name: %s\n", s1.name);
    printf("Roll: %d\n", s1.roll);
    printf("Marks: %.1f\n", s1.marks);

    return 0;
}

class Student:
    def __init__(self, name, roll, marks):
        self.name = name
        self.roll = roll
        self.marks = marks

    def display_details(self):
        print("\nStudent Details")
        print(f"Name: {self.name}")
        print(f"Roll: {self.roll}")
        print(f"Marks: {self.marks:.1f}")

# Simulate user input
print("Enter name: ", end='')
student_name = input()

print("Enter roll number: ", end='')
student_roll = int(input())

print("Enter marks: ", end='')
student_marks = float(input())

# Create a Student object and display details
s1 = Student(student_name, student_roll, student_marks)
s1.display_details()

#include <stdio.h>

int main() {
    int n;

    printf("Enter a number: ");
    scanf("%d", &n);

    if (n % 2 == 0)
        printf("Number is Even");
    else
        printf("Number is Odd");

    return 0;
}

# Simulate user input
print("Enter a number: ", end='')
python_n = int(input())

if python_n % 2 == 0:
    print("Number is Even")
else:
    print("Number is Odd")

#include <stdio.h>

int main() {
    int n, i;

    printf("Enter a number: ");
    scanf("%d", &n);

    for (i = 1; i <= 10; i++) {
        printf("%d x %d = %d\n", n, i, n * i);
    }

    return 0;
}

# Simulate user input
print("Enter a number: ", end='')
python_n_table = int(input())

for i in range(1, 11):
    print(f"{python_n_table} x {i} = {python_n_table * i}")

#include <stdio.h>

int main() {
    int a, b;

    printf("Enter two numbers: ");
    scanf("%d %d", &a, &b);

    if (a > b)
        printf("%d is largest", a);
    else
        printf("%d is largest", b);

    return 0;
}

# Simulate user input
print("Enter two numbers: ", end='')
input_str = input()
python_a, python_b = map(int, input_str.split())

if python_a > python_b:
    print(f"{python_a} is largest")
else:
    print(f"{python_b} is largest")